CREATE TABLE READINGS (
    READID CHAR(36) PRIMARY KEY,
    CUSTID INT,
    LOCID INT,
    METID VARCHAR(32),
    CNSUM DECIMAL(7, 2),
    CNSDT DATETIME,
    CNTYP CHAR(1)
) ENGINE=InnoDB;

GRANT RELOAD, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'mysqlami'@'%';
FLUSH PRIVILEGES;